apiVersion: v1
kind: Secret
metadata:
  name: mlflow-db-secrets
type: Opaque
data:
  # 'mlflow' encoded in base64: bWxmbG93
  POSTGRES_USER: bWxmbG93
  # 'password' encoded in base64: cGFzc3dvcmQ=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  # 'mlflow' encoded in base64: bWxmbG93
  POSTGRES_DB: bWxmbG93